import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './styles/custom-bootstrap.scss';
import './styles/globals.scss';
import Image from 'next/image';
import Link from 'next/link';
import SearchBox from '@/features/SearchBox';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="navbar navbar-expand-lg navbar-light bg-meli shadow-sm">
          <div className="container">
            <div className="row w-100 align-items-center">
              <Link href="/" className="col-2 col-md-auto d-flex">
                <Image
                  className="d-block d-sm-none"
                  src="/logo__small@2x.png"
                  width={39}
                  height={28}
                  alt="Logo de mercado libre"
                />
                <Image
                  className="d-none d-md-block"
                  src="/logo_large_plus@2x.webp"
                  width={134}
                  height={34}
                  alt="Logo de mercado libre"
                />
              </Link>
              <div className="col-10 col-md d-flex justify-content-center justify-content-md-end">
                <SearchBox />
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
