export interface Producto {
  id: string;
  title: string;
  price: {
    currency: string;
    amount: number;
    decimals: number;
  };
  picture: string;
  condition: string;
  free_shipping: boolean;
  sold_quantity: number;
  description: string;
  categories: string[];
}

export const productos: Producto[] = [
  {
    id: "MLA111222",
    title: "iPhone 13 128GB",
    categories: ["Tecnología", "Celulares", "Smartphones"],
    price: { currency: "$", amount: 800000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: true,
    sold_quantity: 23,
    description: "El nuevo iPhone 13 ofrece un rendimiento excepcional, cámara avanzada y batería de larga duración para acompañarte todo el día.",
  },
  {
    id: "MLA333444",
    title: "Samsung Galaxy S22",
    categories: ["Tecnología", "Celulares", "Smartphones"],
    price: { currency: "$", amount: 750000, decimals: 50 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: false,
    sold_quantity: 15,
    description: "Samsung Galaxy S22 con pantalla Dynamic AMOLED 2X, cámara de alta resolución y diseño elegante para usuarios exigentes.",
  },
  {
    id: "MLA555666",
    title: "Xiaomi Redmi Note 11",
    categories: ["Tecnología", "Celulares", "Smartphones"],
    price: { currency: "$", amount: 350000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: true,
    sold_quantity: 30,
    description: "Xiaomi Redmi Note 11 con pantalla AMOLED, batería de gran capacidad y rendimiento fluido para el día a día.",
  },
  {
    id: "MLA777888",
    title: "Huawei P40 Pro",
    categories: ["Tecnología", "Celulares", "Smartphones"],
    price: { currency: "$", amount: 600000, decimals: 99 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: false,
    sold_quantity: 18,
    description: "Huawei P40 Pro con cámara Leica, rendimiento avanzado y diseño sofisticado para fotografía profesional y uso intensivo.",
  },
  {
    id: "MLA999000",
    title: "MacBook Pro 14 pulgadas",
    categories: ["Tecnología", "Computadoras", "Laptops"],
    price: { currency: "$", amount: 3500000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: true,
    sold_quantity: 12,
    description: "MacBook Pro 14 pulgadas con chip M1 Pro, pantalla Liquid Retina XDR y autonomía para profesionales creativos.",
  },
  {
    id: "MLA123456",
    title: "Dell XPS 13",
    categories: ["Tecnología", "Computadoras", "Laptops"],
    price: { currency: "$", amount: 2800000, decimals: 25 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: true,
    sold_quantity: 25,
    description: "Dell XPS 13, ultrabook potente y compacto con pantalla InfinityEdge y materiales premium para máxima portabilidad.",
  },
  {
    id: "MLA654321",
    title: "Apple Watch Series 7",
    categories: ["Tecnología", "Wearables", "Smartwatches"],
    price: { currency: "$", amount: 1200000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: true,
    sold_quantity: 40,
    description: "Apple Watch Series 7 con pantalla más grande, carga rápida y funciones avanzadas de salud y bienestar integradas.",
  },
  {
    id: "MLA112233",
    title: "Samsung Galaxy Watch 4",
    categories: ["Tecnología", "Wearables", "Smartwatches"],
    price: { currency: "$", amount: 900000, decimals: 99 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: false,
    sold_quantity: 22,
    description: "Samsung Galaxy Watch 4 con seguimiento avanzado de salud, diseño moderno y múltiples funciones deportivas y de bienestar.",
  },
  {
    id: "MLA445566",
    title: "Sony WH-1000XM4",
    categories: ["Tecnología", "Audio", "Auriculares"],
    price: { currency: "$", amount: 600000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: true,
    sold_quantity: 50,
    description: "Auriculares Sony WH-1000XM4 con cancelación activa de ruido, sonido envolvente y batería de larga duración para viajes.",
  },
  {
    id: "MLA778899",
    title: "Bose QuietComfort 35 II",
    categories: ["Tecnología", "Audio", "Auriculares"],
    price: { currency: "$", amount: 580000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: false,
    sold_quantity: 35,
    description: "Auriculares Bose QuietComfort 35 II con gran comodidad, sonido claro y cancelación de ruido para una experiencia inmersiva.",
  },
  {
    id: "MLA998877",
    title: "iPad Air 5",
    categories: ["Tecnología", "Tablets"],
    price: { currency: "$", amount: 900000, decimals: 50 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: true,
    sold_quantity: 27,
    description: "iPad Air 5 con chip M1, pantalla Liquid Retina y compatibilidad con Apple Pencil para productividad y creatividad móvil.",
  },
  {
    id: "MLA887766",
    title: "Amazon Fire HD 10",
    categories: ["Tecnología", "Tablets"],
    price: { currency: "$", amount: 350000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: true,
    sold_quantity: 45,
    description: "Tablet Amazon Fire HD 10 con pantalla Full HD, batería de larga duración y acceso a miles de aplicaciones y contenidos.",
  },
  {
    id: "MLA223344",
    title: "Google Pixel 6",
    categories: ["Tecnología", "Celulares", "Smartphones"],
    price: { currency: "$", amount: 650000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: false,
    sold_quantity: 20,
    description: "Google Pixel 6 con cámara excepcional, Android puro y procesador Google Tensor para un rendimiento inteligente y fluido.",
  },
  {
    id: "MLA556677",
    title: "Logitech MX Master 3",
    categories: ["Tecnología", "Accesorios", "Mouse"],
    price: { currency: "$", amount: 120000, decimals: 99 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: true,
    sold_quantity: 60,
    description: "Mouse inalámbrico Logitech MX Master 3 con gran precisión, ergonomía avanzada y múltiples funciones para productividad.",
  },
  {
    id: "MLA889900",
    title: "Razer BlackWidow V3",
    categories: ["Tecnología", "Accesorios", "Teclados"],
    price: { currency: "$", amount: 150000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: false,
    sold_quantity: 25,
    description: "Teclado mecánico Razer BlackWidow V3 para gaming, con retroiluminación RGB y switches de alta durabilidad y respuesta.",
  },
  {
    id: "MLA112244",
    title: "GoPro HERO10 Black",
    categories: ["Tecnología", "Cámaras", "Accesorios"],
    price: { currency: "$", amount: 800000, decimals: 0 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "used",
    free_shipping: true,
    sold_quantity: 19,
    description: "Cámara GoPro HERO10 Black con estabilización avanzada, grabación en 5.3K y resistencia al agua para aventuras extremas.",
  },
  {
    id: "MLA334455",
    title: "Canon EOS Rebel T7",
    categories: ["Tecnología", "Cámaras", "DSLR"],
    price: { currency: "$", amount: 650000, decimals: 75 },
    picture: "https://tayuh2o6fu1ffl9a.public.blob.vercel-storage.com/products/iphone13.webp",
    condition: "new",
    free_shipping: false,
    sold_quantity: 16,
    description: "Cámara Canon EOS Rebel T7 DSLR para principiantes, con calidad profesional, fácil manejo y conectividad inalámbrica.",
  }
]
